output   = "database-models"
no-tests = true
wipe     = true

[psql]
  dbname  = "postgres"
  host    = "localhost"
  port    = 5432
  user    = "postgres"
  pass    = "pass"
  sslmode = "disable"
  blacklist = ["databasechangelog", "databasechangeloglock"]